options, lint

diff --git a/code/templates/code-configmap.yaml b/code/templates/code-configmap.yaml
--- a/code/templates/code-configmap.yaml
+++ b/code/templates/code-configmap.yaml
@@ -10,59 +10,57 @@ data:
 
     # passwordless sudo
     echo "INFO: passwordless sudo"
-    echo $SUDO_PASSWORD | sudo -S -k sed -i -e 's#abc ALL=(ALL:ALL) ALL#abc ALL=(ALL) NOPASSWD:ALL#' /etc/sudoers
+    echo "$SUDO_PASSWORD" | sudo -S -k sed -i -e 's#abc ALL=(ALL:ALL) ALL#abc ALL=(ALL) NOPASSWD:ALL#' /etc/sudoers
 
-    # system packages
-    echo "INFO: installing system packages"
+    # system
     DEBIAN_FRONTEND="noninteractive"; export DEBIAN_FRONTEND
     sudo apt-get update
-    sudo apt-get install -y \
-        apt-transport-https \
-        ca-certificates \
-        curl \
-        python3 \
-        python3-pip \
-        python-is-python3 \
-        software-properties-common
 
     # code extensions
-    printf "INFO: installing code extensions"
-    extensions="golang.go hashicorp.terraform ms-python.python ms-azuretools.vscode-docker ms-vscode.makefile-tools redhat.vscode-yaml"
-    export extensions
-    for extension in $extensions; do
-        /app/code-server/lib/node /app/code-server --extensions-dir /config/extensions --install-extension "$extension" &
-    done
-    while true; do
-        jobs | grep "Running"
-        if [ "$?" -eq 0 ]; then
-            printf "."
-        else
-            echo "done."
-            break
-        fi
-        sleep 3
-    done
+    if [ "$EXTENSIONS_ENABLED" == "true" ]; then
+        printf "INFO: installing code extensions"
+        extensions="golang.go hashicorp.terraform ms-python.python ms-azuretools.vscode-docker ms-vscode.makefile-tools redhat.vscode-yaml"
+        export extensions
+        for extension in $extensions; do
+            /app/code-server/lib/node /app/code-server --extensions-dir /config/extensions --install-extension "$extension" &
+        done
+        while true; do
+            if jobs | grep "Running"; then
+                printf "."
+            else
+                echo "done."
+                break
+            fi
+            sleep 1
+        done
 
-    echo "INFO: validating extensions"
-    for extension in $extensions; do
-        /app/code-server/lib/node /app/code-server --extensions-dir /config/extensions --list-extensions | grep --quiet "$extension"
-        if [ "$?" -eq 0 ]; then
-            echo "INFO: $extension OK"
-        else
-            echo "ERROR: $extension NOT FOUND"
-            exit 1
-        fi
-    done
+        echo "INFO: validating extensions"
+        for extension in $extensions; do
+            if /app/code-server/lib/node /app/code-server --extensions-dir /config/extensions --list-extensions | grep --quiet "$extension"; then
+                echo "INFO: $extension OK"
+            else
+                echo "ERROR: $extension NOT FOUND"
+                exit 1
+            fi
+        done
+    else
+        echo "INFO: EXTENSIONS_ENABLED != true; skipping"
+    fi
 
     # docker per https://docs.docker.com/engine/install/ubuntu/#set-up-the-repository
-    if [ $DIND_ENABLED == "true" ]; then
+    if [ "$DIND_ENABLED" == "true" ]; then
         echo "INFO: installing docker"
+        sudo apt-get install -y --no-install-recommends \
+            apt-transport-https \
+            ca-certificates \
+            curl \
+            software-properties-common
         sudo mkdir -p /etc/apt/keyrings
         sudo bash -c "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg"
         sudo chmod a+r /etc/apt/keyrings/docker.gpg
         sudo bash -c "echo \
-        \"deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
-        $(lsb_release -cs) stable\" | tee /etc/apt/sources.list.d/docker.list"
+    \"deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
+    $(lsb_release -cs) stable\" | tee /etc/apt/sources.list.d/docker.list"
         sudo apt-get update
         sudo apt-get install -y --no-install-recommends docker-ce docker-ce-cli docker-compose-plugin
         sudo usermod -aG docker abc
@@ -78,22 +76,32 @@ data:
     fi
 
     # go per https://go.dev/doc/install
-    if [ $GO_ENABLED == "true" ]; then
+    if [ "$GO_ENABLED" == "true" ]; then
         echo "INFO: installing go"
         sudo rm -rf /usr/local/go
-        curl -sL https://go.dev/dl/go$GO_VERSION.linux-$(dpkg --print-architecture).tar.gz --output ~/go$GO_VERSION.linux-$(dpkg --print-architecture).tar.gz
-        sudo tar -C /usr/local -xzf ~/go$GO_VERSION.linux-$(dpkg --print-architecture).tar.gz
-        rm -f ~/go$GO_VERSION.linux-$(dpkg --print-architecture).tar.gz
+        curl -sL https://go.dev/dl/go"$GO_VERSION".linux-"$(dpkg --print-architecture)".tar.gz --output ~/go"$GO_VERSION".linux-"$(dpkg --print-architecture)".tar.gz
+        sudo tar -C /usr/local -xzf ~/go"$GO_VERSION".linux-"$(dpkg --print-architecture)".tar.gz
+        rm -f ~/go"$GO_VERSION".linux-"$(dpkg --print-architecture)".tar.gz
 
-        grep --quiet '/usr/local/go/bin' ~/.profile
-        if [ "$?" -eq 0 ]; then
+        if grep --quiet '/usr/local/go/bin' ~/.profile; then
             echo "INFO: go in PATH"
         else
             echo "INFO: adding go to PATH"
-            echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.profile
+            echo "export PATH=\$PATH:/usr/local/go/bin" >> ~/.profile
         fi
     else
         echo "INFO: GO_ENABLED != true; skipping"
     fi
 
     echo "INFO: init script complete"
+
+    # python packages
+    if [ "$PYTHON_ENABLED" == "true" ]; then
+        echo "INFO: installing python"
+        sudo apt-get install -y --no-install-recommends \
+            python3 \
+            python3-pip \
+            python-is-python3
+    else
+        echo "INFO: PYTHON_ENABLED != true; skipping"
+    fi
